FROM debian:testing

MAINTAINER Xero-Hige <Gaston.martinez.90@gmail.com>
WORKDIR /

RUN echo "deb http://debian.unnoba.edu.ar/debian/ testing main contrib non-free \
          \ndeb-src http://debian.unnoba.edu.ar/debian/ testing main contrib non-free" > /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y --no-install-recommends aptitude && \
    aptitude install -y \
        wget \
        locales \
        gcc \
        python3-pip \
		python3-setuptools && \
    rm -rf /var/lib/apt/lists/* && \
    aptitude clean

RUN pip3 install gensim --no-cache-dir &&\
    pip3 install twitter --no-cache-dir && \
    pip3 install pika --no-cache-dir && \
    pip3 install pubnub --no-cache-dir && \
    pip3 install Cython --no-cache-dir && \
    pip3 install word2vec --no-cache-dir

RUN apt-get update && \
    aptitude install -y \
        python-pip \
		python-setuptools && \
    rm -rf /var/lib/apt/lists/* && \
    aptitude clean

RUN pip install pika --no-cache-dir && \
    pip install tensorflow-serving-api --no-cache-dir && \
    pip install numpy --no-cache-dir && \
    pip install Cython --no-cache-dir

COPY /src /Magus

WORKDIR /Magus

CMD ["bash","StartMagus.sh"]
