version: '3'

services:
  rabbitmq:
    image: rabbitmq

    ports:
      - "8080:15672"
      - "5672:5672"
      - "5671:5671"

  magus:
    build:
      context: .
      dockerfile: dockerfile-Magus

    depends_on:
      - rabbitmq

    env_file:
      - twitter.env

    volumes:
      - ./vectors:/vectors
      - ./models:/models

    stop_signal: SIGINT