version: '3'

services:
  rabbitmq:
    # Rabbit MQ broker
    image: rabbitmq

    ports:
      - "8080:15672"
      - "5672:5672"
      - "5671:5671"

  magus:
    # Magus Image
    build:
      context: .
      dockerfile: dockerfile-Magus

    depends_on:
      # Rabbit MQ to interconect cores
      - rabbitmq
      # Morgana to classify
      - morgana

    env_file:
      # Keys enviroment file
      - twitter.env

    volumes:
      # Temporal stores
      - ./vectors:/Magus/vectors
      # Word2Vec models folder
      - ./w2v_models:/w2v_models
      # New downloaded tweets folder
      - ./temp_tweets:/tweets

    stop_signal: SIGINT

  the_world:
    # Web Frontend (Interactive world map)
    build:
      context: .
      dockerfile: dockerfile-TheWorld

    ports:
      # Frontend port
      - "8000:8000"

    stop_signal: SIGINT

  morgana:
    # Tensorflow server for the CNN model
    build:
      context: .
      dockerfile: dockerfile-Morgana

    volumes:
      # Model folder
      - ./cnn_model:/MorganaModel

    stop_signal: SIGINT
